version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: siz_cosmeticos_postgres
    restart: always
    ports:
      - "5433:5432"  # Mudamos para porta 5433 externamente, mantendo 5432 internamente
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: siz_cosmeticos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
